Summary:	Main C library
Name:		glibc
Version:	2.17
Release:	1
License:	GPLv3
URL:		http://www.gnu.org/software/libc
Group:		Applications/System
Vendor:		Bildanet
Distribution:	Octothorpe
Source:		http://ftp.gnu.org/gnu/glibc/%{name}-%{version}.tar.xz
%description
This library provides the basic routines for allocating memory,
searching directories, opening and closing files, reading and
writing files, string handling, pattern matching, arithmetic,
and so on.
%prep
%setup -q
%build
install -vdm 755 %{_builddir}/%{name}-build
cd %{_builddir}/%{name}-build
	CFLAGS="%{optflags}" \
	CXXFLAGS="%{optflags}" \
	../%{name}-%{version}/configure \
	--prefix=%{_prefix} \
	--disable-profile \
	--enable-kernel=2.6.25 \
	--libexecdir=%{_libexecdir}
make %{?_smp_mflags}
%check
cd %{_builddir}/glibc-build
make -k check |& tee %{_specdir}/%{name}-check.log || true
%install
rm -rf %{_buildrootdir}/*
cd %{_builddir}/glibc-build
#	Create directories
install -vdm 755 %{buildroot}%{_libdir}/locale
install -vdm 755 %{buildroot}/etc/ld.so.conf.d
make install_root=%{buildroot} install
cp -v %{_builddir}/%{name}-%{version}/sunrpc/rpc/*.h	%{buildroot}%{_includedir}/rpc
cp -v %{_builddir}/%{name}-%{version}/sunrpc/rpcsvc/*.h	%{buildroot}%{_includedir}/rpcsvc
cp -v %{_builddir}/%{name}-%{version}/nis/rpcsvc/*.h	%{buildroot}%{_includedir}/rpcsvc
#	Install locale generation script and config file
#	Remove unwanted cruft
rm -rf %{buildroot}%{_infodir}
rm -rf %{buildroot}/var
find %{buildroot}%{_libdir} -name '*.la' -delete
#	Install configuration files
cat > %{buildroot}/etc/nsswitch.conf <<- "EOF"
#	Begin /etc/nsswitch.conf
	passwd: files
	group: files
	shadow: files

	hosts: files dns
	networks: files

	protocols: files
	services: files
	ethers: files
	rpc: files
#	End /etc/nsswitch.conf
EOF
cat > %{buildroot}/etc/ld.so.conf <<- "EOF"
#	Begin /etc/ld.so.conf
	/usr/local/lib
	include /etc/ld.so.conf.d/*.conf
EOF
cat > %{buildroot}/etc/locale-gen.conf <<- "EOF"
# Configuration file for locale-gen
#
# lists of locales that are to be generated by the locale-gen command.
#
# Each line is of the form:
#
#     <locale> <charset>
#
#  where <locale> is one of the locales given in /usr/share/i18n/locales
#  and <charset> is one of the character sets listed in /usr/share/i18n/charmaps
#
#  Examples:
#  en_US ISO-8859-1
#  en_US.UTF-8 UTF-8
#  de_DE ISO-8859-1
#  de_DE@euro ISO-8859-15
#
#  The locale-gen command will generate all the locales,
#  placing them in /usr/lib/locale.
#
cs_CZ.UTF-8	UTF-8
de_DE		ISO-8859-1
de_DE@euro	ISO-8859-15
de_DE.UTF-8	UTF-8
en_GB.UTF-8	UTF-8
en_HK		ISO-8859-1
en_PH		ISO-8859-1
en_US		ISO-8859-1
en_US.UTF-8	UTF-8
es_MX		ISO-8859-1
fa_IR		UTF-8
fr_FR		ISO-8859-1
fr_FR@euro	ISO-8859-15
fr_FR.UTF-8	UTF-8
it_IT		ISO-8859-1
it_IT.UTF-8	UTF-8
ja_JP		EUC-JP
ru_RU.KOI8-R	KOI8-R
ru_RU.UTF-8	UTF-8
tr_TR.UTF-8	UTF-8
zh_CN.GB18030	GB18030
EOF
cat > %{buildroot}/sbin/locale-gen.sh <<- "EOF"
#!/bin/sh
set -e
LOCALEGEN=/etc/locale-gen.conf
LOCALES=/usr/share/i18n/locales
if [ -n "$POSIXLY_CORRECT" ]; then
  unset POSIXLY_CORRECT
fi
[ -f $LOCALEGEN -a -s $LOCALEGEN ] || exit 0;
# Remove all old locale dir and locale-archive before generating new
# locale data.
[ -d /usr/lib/locale ] ||  mkdir -pv /usr/lib/locale
rm -rf /usr/lib/locale/* || true
umask 022
is_entry_ok() {
  if [ -n "$locale" -a -n "$charset" ] ; then
    true
  else
    echo "error: Bad entry '$locale $charset'"
    false
  fi
}
echo "Generating locales..."
while read locale charset; do \
	case $locale in \#*) continue;; "") continue;; esac; \
	is_entry_ok || continue
	echo -n "  `echo $locale | sed 's/\([^.\@]*\).*/\1/'`"; \
	echo -n ".$charset"; \
	echo -n `echo $locale | sed 's/\([^\@]*\)\(\@.*\)*/\2/'`; \
	echo -n '...'; \
	if [ -f $LOCALES/$locale ]; then input=$locale; else \
	input=`echo $locale | sed 's/\([^.]*\)[^@]*\(.*\)/\1\2/'`; fi; \
	localedef -i $input -c -f $charset -A /usr/share/locale/locale.alias $locale; \
	echo ' done'; \
done < $LOCALEGEN
echo "Generation complete."
EOF
%find_lang %{name} $RPM_BUILD_ROOT libc glibc.lang
%post
printf "Creating ldconfig cache\n";/sbin/ldconfig
printf "Creating locale files\n";/sbin/locale-gen.sh
%clean
rm -rf %{buildroot}/* %{_builddir}/*
%files -f %{name}.lang
%defattr(-,root,root)
#	Configuration
%config(noreplace) /etc/ld.so.conf
%config(noreplace) /etc/locale-gen.conf
%config /etc/nsswitch.conf
%dir /etc/ld.so.conf.d
%config /etc/rpc
%config /etc/ld.so.cache
#	Executables
%{_bindir}/*
%attr(755, root, root) /sbin/locale-gen.sh
/sbin/ldconfig
/sbin/sln
#	Includes
%{_includedir}/*.h
%{_includedir}/arpa/*.h
%{_includedir}/bits/*.h
%{_includedir}/bits/stab.def
%{_includedir}/gnu/*.h
%{_includedir}/net/*.h
%{_includedir}/netash/*.h
%{_includedir}/netatalk/*.h
%{_includedir}/netax25/*.h
%{_includedir}/neteconet/*.h
%{_includedir}/netinet/*.h
%{_includedir}/netipx/*.h
%{_includedir}/netiucv/*.h
%{_includedir}/netpacket/*.h
%{_includedir}/netrom/*.h
%{_includedir}/netrose/*.h
%{_includedir}/nfs/*.h
%{_includedir}/protocols/*.h
%{_includedir}/rpc/*.h
%{_includedir}/rpcsvc/*.h
%{_includedir}/scsi/*.h
%{_includedir}/sys/*.h
#	Libraries
/lib/*
%{_libdir}/*.a
%{_libdir}/*.o
%{_libdir}/*.so
%{_libdir}/audit/*.so
%{_libdir}/gconv/*.so
%{_libdir}/gconv/gconv-modules
#	Library executables
%{_libexecdir}/pt_chown
%{_libexecdir}/getconf/*
%{_sbindir}/*
#	Internationalization character maps
%{_datarootdir}/i18n/charmaps/*.gz
%{_datarootdir}/i18n/locales/*
%lang(be) %{_datarootdir}/locale/be/LC_MESSAGES/*.mo
%lang(bg) %{_datarootdir}/locale/bg/LC_MESSAGES/*.mo
%lang(ca) %{_datarootdir}/locale/ca/LC_MESSAGES/*.mo
%lang(cs) %{_datarootdir}/locale/cs/LC_MESSAGES/*.mo
%lang(da) %{_datarootdir}/locale/da/LC_MESSAGES/*.mo
%lang(de) %{_datarootdir}/locale/de/LC_MESSAGES/*.mo
%lang(el) %{_datarootdir}/locale/el/LC_MESSAGES/*.mo
%lang(en_GB) %{_datarootdir}/locale/en_GB/LC_MESSAGES/*.mo
%lang(eo) %{_datarootdir}/locale/eo/LC_MESSAGES/*.mo
%lang(es) %{_datarootdir}/locale/es/LC_MESSAGES/*.mo
%lang(fi) %{_datarootdir}/locale/fi/LC_MESSAGES/*.mo
%lang(fr) %{_datarootdir}/locale/fr/LC_MESSAGES/*.mo
%lang(gl) %{_datarootdir}/locale/gl/LC_MESSAGES/*.mo
%lang(hr) %{_datarootdir}/locale/hr/LC_MESSAGES/*.mo
%lang(hu) %{_datarootdir}/locale/hu/LC_MESSAGES/*.mo
%lang(id) %{_datarootdir}/locale/id/LC_MESSAGES/*.mo
%lang(it) %{_datarootdir}/locale/it/LC_MESSAGES/*.mo
%lang(ja) %{_datarootdir}/locale/ja/LC_MESSAGES/*.mo
%lang(ko) %{_datarootdir}/locale/ko/LC_MESSAGES/*.mo
%{_datarootdir}/locale/locale.alias
%lang(lt) %{_datarootdir}/locale/lt/LC_MESSAGES/*.mo
%lang(nb) %{_datarootdir}/locale/nb/LC_MESSAGES/*.mo
%lang(nl) %{_datarootdir}/locale/nl/LC_MESSAGES/*.mo
%lang(pl) %{_datarootdir}/locale/pl/LC_MESSAGES/*.mo
%lang(pt) %{_datarootdir}/locale/pt_BR/LC_MESSAGES/*.mo
%lang(ru) %{_datarootdir}/locale/ru/LC_MESSAGES/*.mo
%lang(rw) %{_datarootdir}/locale/rw/LC_MESSAGES/*.mo
%lang(sk) %{_datarootdir}/locale/sk/LC_MESSAGES/*.mo
%lang(sv) %{_datarootdir}/locale/sv/LC_MESSAGES/*.mo
%lang(tr) %{_datarootdir}/locale/tr/LC_MESSAGES/*.mo
%lang(vi) %{_datarootdir}/locale/vi/LC_MESSAGES/*.mo
%lang(zh_CN) %{_datarootdir}/locale/zh_CN/LC_MESSAGES/*.mo
%lang(zh_TW) %{_datarootdir}/locale/zh_TW/LC_MESSAGES/*.mo
%changelog
*	Sun Mar 24 2013 baho-utot <baho-utot@columbus.rr.com> 2.17-1
-	Update version
*	Wed Jan 30 2013 baho-utot <baho-utot@columbus.rr.com> 2.16-1
-	Initial build.	First version
